### ISSUE TITLE
Compile for 5.1.1 got error

### ISSUE THREAD

**Issue by mkygogo** [Ji-Rath/MassAIExample#3]
MassStateTreeClaimSmartObjectTaskPlus.h(25): [] Unable to find 'class', 'delegate', 'enum', or 'struct' with name 'EMassSmartObjectClaimResult'
  MassStateTreeSmartObjectEvaluatorPlus.h(22): [] Unable to find 'class', 'delegate', 'enum', or 'struct' with name 'FMassSmartObjectRequestResult'

**Comment by EllyKher** [comment]
@mkygogo that issue got fixed in this update ;) 
https://github.com/Ji-Rath/MassAITesting/pull/6

**Comment by huuthinhnguyen0309** [comment]
I still get this error 
MassStateTreeClaimSmartObjectTaskPlus.h(25): [] Unable to find 'class', 'delegate', 'enum', or 'struct' with name 'EMassSmartObjectClaimResult'

**Comment by Ji-Rath** [comment]
I'll be closing this issue for now as these bugs should be resolved with the latest release, but feel free to reopen if you continue to have issues.
